# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import chunk_pb2 as chunk__pb2


class ClassificationServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.inquire = channel.stream_unary(
                '/ClassificationServer/inquire',
                request_serializer=chunk__pb2.Image.SerializeToString,
                response_deserializer=chunk__pb2.Response.FromString,
                )


class ClassificationServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def inquire(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClassificationServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'inquire': grpc.stream_unary_rpc_method_handler(
                    servicer.inquire,
                    request_deserializer=chunk__pb2.Image.FromString,
                    response_serializer=chunk__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ClassificationServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ClassificationServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def inquire(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/ClassificationServer/inquire',
            chunk__pb2.Image.SerializeToString,
            chunk__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
